### PR TITLE
Do not call random.choice for fields which have no valid choices

### PR DESCRIPTION
**Pull request by lampslave**
In case of `ModelChoiceField(queryset=MyModel.objects.none(), required=False)` for example.

### CODE REVIEW

**Comment by lampslave** [comment]
I fear `model_choice_field_data` also must to be fixed.

**Comment by GeyseR** [comment]
Thanks!

**Comment by lampslave** [comment]
I'm sorry for the panic, actually, `ModelChoiceField` always have "empty" choice ("valid" in this case), and this issue is related only to fields from django_select2 and ChoiceField. Anyway, even with this fix `ModelSelect2MultipleField` can't be filled with data (`model_choice_field_data` raises `TypeError`), so I'll try to prepare a common fix for this.

**Comment by lampslave** [comment]
Please see #53

**Pull request merged**
